// Code generated by MockGen. DO NOT EDIT.
// Source: sharing/rabbit/channel (interfaces: ChannelInterface,RChannelInterface)

// Package mock_channel is a generated GoMock package.
package channel

import (
	gomock "github.com/golang/mock/gomock"
	amqp "github.com/streadway/amqp"
	config "gitlab.nixdev.co/golang-general/rabbit-mq-go/config"
	connection "gitlab.nixdev.co/golang-general/rabbit-mq-go/connection"
	reflect "reflect"
)

// MockChannelInterface is a mock of ChannelInterface interface
type MockChannelInterface struct {
	ctrl     *gomock.Controller
	recorder *MockChannelInterfaceMockRecorder
}

// MockChannelInterfaceMockRecorder is the mock recorder for MockChannelInterface
type MockChannelInterfaceMockRecorder struct {
	mock *MockChannelInterface
}

// NewMockChannelInterface creates a new mock instance
func NewMockChannelInterface(ctrl *gomock.Controller) *MockChannelInterface {
	mock := &MockChannelInterface{ctrl: ctrl}
	mock.recorder = &MockChannelInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChannelInterface) EXPECT() *MockChannelInterfaceMockRecorder {
	return m.recorder
}

// BindQueue mocks base method
func (m *MockChannelInterface) BindQueue(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindQueue", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BindQueue indicates an expected call of BindQueue
func (mr *MockChannelInterfaceMockRecorder) BindQueue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindQueue", reflect.TypeOf((*MockChannelInterface)(nil).BindQueue), arg0)
}

// Close mocks base method
func (m *MockChannelInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockChannelInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockChannelInterface)(nil).Close))
}

// Create mocks base method
func (m *MockChannelInterface) Create(arg0 connection.RConnectionInterface) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockChannelInterfaceMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChannelInterface)(nil).Create), arg0)
}

// ExchangeDeclare mocks base method
func (m *MockChannelInterface) ExchangeDeclare(arg0 config.ExchangeConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeDeclare", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExchangeDeclare indicates an expected call of ExchangeDeclare
func (mr *MockChannelInterfaceMockRecorder) ExchangeDeclare(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeDeclare", reflect.TypeOf((*MockChannelInterface)(nil).ExchangeDeclare), arg0)
}

// Publish mocks base method
func (m *MockChannelInterface) Publish(arg0 string, arg1 amqp.Publishing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish
func (mr *MockChannelInterfaceMockRecorder) Publish(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockChannelInterface)(nil).Publish), arg0, arg1)
}

// QueueDeclare mocks base method
func (m *MockChannelInterface) QueueDeclare(arg0 config.QueueConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueDeclare", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueDeclare indicates an expected call of QueueDeclare
func (mr *MockChannelInterfaceMockRecorder) QueueDeclare(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueDeclare", reflect.TypeOf((*MockChannelInterface)(nil).QueueDeclare), arg0)
}

// MockRChannelInterface is a mock of RChannelInterface interface
type MockRChannelInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRChannelInterfaceMockRecorder
}

// MockRChannelInterfaceMockRecorder is the mock recorder for MockRChannelInterface
type MockRChannelInterfaceMockRecorder struct {
	mock *MockRChannelInterface
}

// NewMockRChannelInterface creates a new mock instance
func NewMockRChannelInterface(ctrl *gomock.Controller) *MockRChannelInterface {
	mock := &MockRChannelInterface{ctrl: ctrl}
	mock.recorder = &MockRChannelInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRChannelInterface) EXPECT() *MockRChannelInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockRChannelInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockRChannelInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRChannelInterface)(nil).Close))
}

// Consume mocks base method
func (m *MockRChannelInterface) Consume(arg0, arg1 string, arg2, arg3, arg4, arg5 bool, arg6 amqp.Table) (<-chan amqp.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(<-chan amqp.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume
func (mr *MockRChannelInterfaceMockRecorder) Consume(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockRChannelInterface)(nil).Consume), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// ExchangeDeclare mocks base method
func (m *MockRChannelInterface) ExchangeDeclare(arg0, arg1 string, arg2, arg3, arg4, arg5 bool, arg6 amqp.Table) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeDeclare", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExchangeDeclare indicates an expected call of ExchangeDeclare
func (mr *MockRChannelInterfaceMockRecorder) ExchangeDeclare(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeDeclare", reflect.TypeOf((*MockRChannelInterface)(nil).ExchangeDeclare), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// Publish mocks base method
func (m *MockRChannelInterface) Publish(arg0, arg1 string, arg2, arg3 bool, arg4 amqp.Publishing) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish
func (mr *MockRChannelInterfaceMockRecorder) Publish(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockRChannelInterface)(nil).Publish), arg0, arg1, arg2, arg3, arg4)
}

// Qos mocks base method
func (m *MockRChannelInterface) Qos(arg0, arg1 int, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Qos", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Qos indicates an expected call of Qos
func (mr *MockRChannelInterfaceMockRecorder) Qos(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Qos", reflect.TypeOf((*MockRChannelInterface)(nil).Qos), arg0, arg1, arg2)
}

// QueueBind mocks base method
func (m *MockRChannelInterface) QueueBind(arg0, arg1, arg2 string, arg3 bool, arg4 amqp.Table) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueBind", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueueBind indicates an expected call of QueueBind
func (mr *MockRChannelInterfaceMockRecorder) QueueBind(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueBind", reflect.TypeOf((*MockRChannelInterface)(nil).QueueBind), arg0, arg1, arg2, arg3, arg4)
}

// QueueDeclare mocks base method
func (m *MockRChannelInterface) QueueDeclare(arg0 string, arg1, arg2, arg3, arg4 bool, arg5 amqp.Table) (amqp.Queue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueDeclare", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(amqp.Queue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueueDeclare indicates an expected call of QueueDeclare
func (mr *MockRChannelInterfaceMockRecorder) QueueDeclare(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueDeclare", reflect.TypeOf((*MockRChannelInterface)(nil).QueueDeclare), arg0, arg1, arg2, arg3, arg4, arg5)
}
